CC = clang
STRIP = strip
OBJS = txmon.o
CFLAGS = -std=gnu99 -DLINUX -I../../ -O2 -Wall -Wno-unused-value -fpic
CLIBS = -L ../../ -lpseudonode -lpthread -ldl -Wl,-R.

txmon: txmon.o
	$(CC) $(CFLAGS) -o txmon $(OBJS) $(CLIBS)
	$(STRIP) txmon
	cp txmon txmon.macosx

txmon.o: txmon.c

clean:
	rm -f $(OBJS) txmon.o

